/** Predefined tags for hand review posts */
export const HAND_TAGS = [
  'bluff',
  'value-bet',
  'thin-value',
  'check-raise',
  'three-bet',
  'four-bet',
  'squeeze',
  'cold-call',
  'set-mining',
  'drawing',
  'overbet',
  'slow-play',
  'float',
  'probe-bet',
  'donk-bet',
  'multiway',
  'heads-up',
  'short-stack',
  'deep-stack',
  'ICM',
  'bubble',
  'final-table',
  'cooler',
  'bad-beat',
  'hero-call',
  'hero-fold',
  'exploitative',
  'GTO',
  'live-read',
  'solver-spot',
] as const;

export type HandTag = (typeof HAND_TAGS)[number];
